server {
    listen 8443 ssl;
    server_name _;
    access_log /dev/stdout;

    # Send error logs to stderr (or /dev/stdout if preferred)
    error_log /dev/stderr;

    ssl_certificate     /etc/nginx/conf.d/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/nginx-selfsigned.key;

    ssl_client_hello_by_lua_block {
        local ja4 = require "resty.ja4"
        ja4.configure({ hash = true })
        ja4.compute()
    }

    header_filter_by_lua_block {
        local ja4 = require "resty.ja4"
        local ja4h = require "resty.ja4h"
        ja4h.configure({ hash = true })

        local tls_fp = ja4.get()
        if tls_fp then
            ngx.header["X-JA4"] = tls_fp
        end

        local http_fp = ja4h.compute()
        if http_fp then
            ngx.header["X-JA4H"] = http_fp
        end
    }

    location / {
        return 200 "ok";
    }
}
