
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
  worker_connections  1024;
}


http {
  include       mime.types;
  default_type  application/octet-stream;

  #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
  #                  '$status $body_bytes_sent "$http_referer" '
  #                  '"$http_user_agent" "$http_x_forwarded_for"';

  #access_log  logs/access.log  main;

  sendfile        on;
  #tcp_nopush     on;

  #keepalive_timeout  0;
  keepalive_timeout  65;

  #gzip  on;

  server {
    listen       80;
    server_name  _;

    #access_log  logs/host.access.log  main;

    location / {
      root   html;
      index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
      root   html;
    }
  }

  server {
    listen 8443 ssl;
    server_name _;
    access_log /dev/stdout;
    error_log /dev/stderr;

    ssl_certificate     /etc/openresty/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/openresty/ssl/nginx-selfsigned.key;

    ssl_client_hello_by_lua_block {
      local ja4 = require "resty.ja4"
      ja4.configure({ hash = true })
      ja4.compute()
    }

    header_filter_by_lua_block {
      local ja4 = require "resty.ja4"
      local ja4h = require "resty.ja4h"
      ja4h.configure({ hash = true })

      local tls_fp = ja4.get()
      if tls_fp then
      ngx.header["X-JA4"] = tls_fp
      end

      local http_fp = ja4h.compute()
      if http_fp then
      ngx.header["X-JA4H"] = http_fp
      end
    }

    location / {
      return 200 "ok";
    }
  }

}
