FROM apache/kafka:4.3.1

ADD https://linkedin.jfrog.io/artifactory/cruise-control/com/linkedin/cruisecontrol/cruise-control-metrics-reporter/3.0.4/cruise-control-metrics-reporter-3.0.4.jar /opt/kafka/libs/cruise-control-metrics-reporter-3.0.4.jar

