FROM apache/kafka:4.0.2

ADD https://linkedin.jfrog.io/artifactory/cruise-control/com/linkedin/cruisecontrol/cruise-control-metrics-reporter/2.5.146/cruise-control-metrics-reporter-2.5.146.jar /cruise-control-metrics-reporter-2.5.146.jar
